version: '3'

services:
  angular-app:
    container_name: angular-app
    build: ./app
    ports:
      - "4200:4200"
    volumes:
      - angular_app_data:/app
#      - ./app/web-wise:/app # While developing to not have to rebuild the image
    depends_on:
      - api

  api:
    container_name: api
    build: ./api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - api_data:/app
      - ./api:/app # While developing to not have to rebuild the image
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  model:
    container_name: model
    build: ./model
    env_file:
      - .env
    volumes:
      - model_data:/app
    depends_on:
      - chroma

  chroma:
    container_name: chroma
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

volumes:
  api_data:
  db_data:
  angular_app_data:
  chromadb_data:
  model_data:
